# Generated by Django 5.2.6 on 2025-11-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0003_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='property',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
