# Generated by Django 5.2.6 on 2025-11-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0004_rename_created_at_inquiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
