# Generated by Django 5.2.6 on 2025-11-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0006_inquiry_email_inquiry_message_inquiry_property_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
