# Generated by Django 5.2.6 on 2025-11-14 11:04

import realestate_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0007_delete_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='plot_area',
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='super_builtup_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Flat', 'Flat'), ('Villa', 'Villa'), ('Office', 'Office'), ('Shop', 'Shop'), ('Showroom', 'Showroom'), ('Plot', 'Plot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=realestate_app.models.property_image_upload),
        ),
    ]
